parameters:
- name: serviceconnectionName
  displayName: serviceconnectionName used to deploy in all environments
  type: string
  default: 'reg-dev-spn'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistry: 'vishacr321' ## Change the ACR Name
  azureSubscriptionEndpoint: 'reg-dev-spn' ### Change the service connection Name
  resourceGroupPrefix: 'vishrg' # Change the RG Name'
  ACRServiceConnection: 'acr-spn' ## Change ACR service connection Name

stages:
##################################################################
###                     Development Stage           ###############
####################################################################
- stage: DEV_deploy
  displayName: deploy_DEV
  jobs:
  - template: deploy.yml
    parameters:
      serviceconnectionName: ${{ parameters.serviceconnectionName }}
      
####################################################################
###                          TEST Stage             ###############
##################################################################
- stage: TEST_deploy
  displayName: deploy_TEST
  dependsOn:
  - DEV_deploy
  jobs:
  - template: deploy.yml
    parameters:
      serviceconnectionName: ${{ parameters.serviceconnectionName }}                                   
####################################################################
####   UAT Stage                                    ################
####################################################################
- stage: UAT_deploy
  displayName: deploy_UAT
  dependsOn:
  - TEST_deploy
  jobs:
  - template: deploy.yml
    parameters:
      serviceconnectionName: ${{ parameters.serviceconnectionName }}
####################################################################
####                PROD Stage                      ###############
###################################################################
- stage: PROD_deploy
  displayName: deploy_PROD
  dependsOn:
  - UAT_deploy
  jobs:
  - template: deploy.yml
    parameters:
      serviceconnectionName: ${{ parameters.serviceconnectionName }}

