parameters:
- name: serviceconnectionName
  type: string
  default: 'reg-dev-spn'

jobs:
- job: BuildAndPush
  displayName: 'Build and Push Image'
  steps:

  - script: |
      docker build -t app:latest .
      displayName: 'Build Docker Image'
      
  - script: |
      displayName: 'Run tests'    # Commands to install dependencies and run tests
      npm install
      npm test

#   - task: Docker@2
#     inputs:
#       containerRegistry: '$(ACRServiceConnection)' # Name of your Azure Container Registry service connection
#       repository: '$(azureContainerRegistry)/app' # Name of your ACR repository
#       command: 'push'
#       tags: 'latest' # Tag for your Docker image

# - job: Deploy
#   displayName: 'Deploy to AKS'
#   dependsOn: BuildAndPush
#   steps:
#   - task: Kubernetes@1
#     displayName: 'Deploy to AKS'
#     inputs:
#       connectionType: 'Azure Resource Manager'
#       azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
#       azureResourceGroup: '${{ parameters.resourceGroup }}'
#       kubernetesCluster: '${{ parameters.environment }}'
#       command: 'apply'
#       arguments: '-f k8s\deployment.yml' 
